# -*- coding: utf-8 -*-
"""PILLOW實戰_20241121.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l7L6gc713cG0uT0W5HxLZCaLwe98hfXg

https://steam.oxxostudio.tw/category/python/example/image-watermark.html
"""

!pip install Pillow

from PIL import Image
img = Image.open('./watermark-photo.jpg')    # 開啟風景圖
icon = Image.open('./watermark-icon.png')   # 開啟浮水印 icon
img.paste(icon, (0,0), icon)     # 將風景圖貼上 icon
img.save('./ok.jpg')             # 存檔為 ok.jpg

img_w, img_h = img.size      # 取得風景圖尺寸
icon_w, icon_h = icon.size   # 取得 icon 尺寸
x = int((img_w-icon_w)/2)    # 計算置中時 icon 左上角的 x 座標
y = int((img_h-icon_h)/2)    # 計算置中時 icon 左上角的 y 座標

img.paste(icon, (x, y), icon)   # 設定 icon 左上角座標
img.save('./ok2.jpg')